---
title: Penerbit Ahlan
timezone: UTC
collections:
  agen:
    title: Agen
    output: true
    permalink: "/agen/:path/"
  kabars:
    title: Kabars
    output: true
    permalink: "/kabar/:path/"
  posts:
    title: Posts
    output: true
  produks:
    title: Produks
    output: true
    permalink: "/services/:path/"
  team:
    title: Team
    output: true
    permalink: "/team/:path/"
  testimonials:
    title: Testimonials
    output: true
    permalink: "/testimonials/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: produks
  values:
    layout: service
    bodyClass: page-services-single
- scope:
    path: ''
    type: kabars
  values:
    layout: service
    bodyClass: page-services-single
- scope:
    path: images
  values:
    image: true
baseurl: ''
exclude:
- README.md
permalink: pretty
sass:
  style: compact
google_analytics_id: UA-35557865-2
plugins:
- jekyll-environment-variables
