baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Penerbit Ahlan'

collections:
  produks:
    output: true
    permalink: /services/:path/
  kabars:
    output: true
    permalink: /kabar/:path/
  agen:
    output: true
    permalink: /agen/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/

defaults:
  - scope:
      type: produks
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      type: kabars
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: UA-35557865-2

plugins:
  - jekyll-environment-variables
